INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('USERS');
INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('ADMIN');

INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Jackson Almeida','$2a$10$kbt3fVE5i/Bpe4x/u0M/LuzwpCsJhC3RsfgPJU50d1kfNnzJusc2q');
INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Elisama Marques','$2a$10$kbt3fVE5i/Bpe4x/u0M/LuzwpCsJhC3RsfgPJU50d1kfNnzJusc2q');

INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (2,2);