INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('USERS');
INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('ADMIN');

INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Jackson Almeida','123456');
INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Elisama Marques','123456');

INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (2,2);