INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('USERS');
INSERT INTO TB_ROLE(ROLE_NAME) VALUES ('ADMIN');

INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Jackson Almeida','$2a$10$kbt3fVE5i/Bpe4x/u0M/LuzwpCsJhC3RsfgPJU50d1kfNnzJusc2q');
INSERT INTO TB_PLAYER(NAME, PASSWORD) VALUES ('Elisama Marques','$2a$10$kbt3fVE5i/Bpe4x/u0M/LuzwpCsJhC3RsfgPJU50d1kfNnzJusc2q');

INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO TB_PLAYER_ROLE(PLAYER_ID, ROLE_ID) VALUES (2,2);

INSERT INTO "PUBLIC"."TB_CARD"("ID","EDITION","LANGUAGE","NAME","PRICE","STATUS_CARD")VALUES(1,'2 VERSÃO',2,'Zappts',100.0,1);
INSERT INTO "PUBLIC"."TB_CARD"("ID","EDITION","LANGUAGE","NAME","PRICE","STATUS_CARD")VALUES(2,'3 VERSÃO',2,'Zappts 2',100.0,1);

INSERT INTO "PUBLIC"."TB_LIST_CARD_PLAYER"("NUMBER_LIST","CARD_ID","PLAYER_ID")VALUES(1,1,1);
INSERT INTO "PUBLIC"."TB_LIST_CARD_PLAYER"("NUMBER_LIST","CARD_ID","PLAYER_ID")VALUES(1,1,2);
INSERT INTO "PUBLIC"."TB_LIST_CARD_PLAYER"("NUMBER_LIST","CARD_ID","PLAYER_ID")VALUES(2,2,2);